#!/bin/bash

BUILD=build/m0-fk
BOOTLOADER=${BUILD}/bootloader/bootloader.bin
PROGRAM=${BUILD}/blink/blink-pic-fkb.bin
PROGRAM_SIZE=$(stat -c%s "$PROGRAM")

PROGRAM_1_START=16384
PROGRAM_2_START=$(expr $PROGRAM_1_START + $PROGRAM_SIZE)
PROGRAM_1_START_HEX=$(printf "0x%x" $PROGRAM_1_START)
PROGRAM_2_START_HEX=$(printf "0x%x" $PROGRAM_2_START)

PROGRAM_2_START_HEX=0x10000

echo "Program Size: $PROGRAM_SIZE"
echo "Program 1: $PROGRAM_1_START $PROGRAM_1_START_HEX"
echo "Program 2: $PROGRAM_2_START $PROGRAM_2_START_HEX"

JLinkExe -if SWD -device ATSAMD21G18 -speed 4000 <<EOF
log jlink.log
exitonerror 1
connect
sleep 100
r
sleep 100
loadfile $BOOTLOADER,0x0000
sleep 100
loadfile $PROGRAM,$PROGRAM_1_START_HEX
sleep 100
loadfile $PROGRAM,$PROGRAM_2_START_HEX
r
q
EOF
