#+TITLE:	README for arduino-osh
#+AUTHOR:	Jacob Lewallen
#+EMAIL:	jacob@conservify.org

* Overview

  This began as a fork of os.h (https://github.com/adamheinrich/os.h) that works
  on ATSAMD21 based Arduino devices and has evolved considerably, pulling in
  functionality from CMSIS RTOS and a few other places.

  This now works great on Cortex-M4 devices, like the ATSAMD51.

* Future Work
** TODO Priority levels
** TODO OS level buffer handling
** TODO Character and block abstractions for hardware
** TODO Semaphores

* License

  This software is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option) any
  later version.
  
  This is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE. See the GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this source code.  If not, see <http://www.gnu.org/licenses/>.

* EOF

