#pragma once

#include "hal/hal.h"
#include "hal/metal/metal_network.h"
#include "hal/metal/metal_memory.h"
#include "hal/metal/metal_qspi.h"
#include "hal/metal/metal_gps.h"
#include "hal/metal/metal_battery_gauge.h"
#include "hal/metal/metal_buttons.h"
#include "hal/metal/metal_modmux.h"
#include "hal/metal/metal_ipc.h"
#include "hal/metal/metal_sd_card.h"
#include "hal/metal/metal_lora.h"
#include "hal/metal/metal_leds.h"
#include "hal/metal/pin_modmux.h"
#include "hal/metal/spi_flash.h"
