#!/bin/bash

set -e

FK_LORA_APP_EUI=0000000000000000
FK_LORA_APP_KEY=39e98dbaa08feed53d5f68d43d0ef981
if [ -z $2 ]; then
    PORT=80
else
    PORT=$2
fi

fkc --address $1 --port $PORT --lora-app-eui $FK_LORA_APP_EUI --lora-app-key $FK_LORA_APP_KEY
