#!/bin/bash

PROGRAM=fk-weather-sidecar.bin

if [ ! -f $PROGRAM ]; then
    PROGRAM=build/samd09/modules/weather/sidecar/fk-weather-sidecar.bin
fi

ls -alh $PROGRAM
sha1sum $PROGRAM

EXTRA_ARGS=""
if [ "$(hostname 2> /dev/null)" = "JACOB-WORK" ]; then
    EXTRA_ARGS="-SelectEmuBySN 801000989 "
fi

JLinkExe -if SWD -device ATSAMD09D14A -speed 4000 $EXTRA_ARGS <<EOF
exitonerror 1
connect
exec SetRTTSearchRanges 0x20000000 64
sleep 100
r
sleep 100
loadfile $PROGRAM,0x0000
sleep 100
r
q
EOF
