#!/bin/bash

PROGRAM=fk-weather-sidecar-normal.bin

JLinkExe -if SWD -device ATSAMD09D14A -speed 4000 <<EOF
exitonerror 1
connect
h
exec SetRTTSearchRanges 0x20000000 64
sleep 100
r
sleep 100
loadfile $PROGRAM,0x0000
sleep 100
r
sleep 100
go
q
EOF
