#!/bin/bash

BOOTLOADER=fkbl-fkb.bin
PROGRAM=fk-bundled-fkb.bin

JLinkExe -if SWD -device ATSAMD51P20 -speed 4000 -RTTTelnetPort 19021 <<EOF
exitonerror 1
connect
h
exec SetRTTSearchRanges 0x20000000 64
sleep 100
r
sleep 100
loadfile $BOOTLOADER,0x0000
sleep 100
loadfile $PROGRAM,0x8000
sleep 100
r
sleep 1000
go
EOF
