#!/bin/bash

EXTRA_ARGS=""
if [ "$(hostname 2> /dev/null)" = "JACOB-WORK" ]; then
    EXTRA_ARGS="-select usb=269402795"
fi
if [ "$(hostname 2> /dev/null)" = "JACOB-HOME" ]; then
    EXTRA_ARGS="-select usb=269402795"
fi

JLinkGDBServer -if SWD -device ATSAMD09D14A -port 5331 -RTTTelnetPort 9500 $EXTRA_ARGS
