string(RANDOM LENGTH 5 ALPHABET 0123456789 RANDOM_SEED)
math(EXPR RANDOM_SEED "${RANDOM_SEED} + 0")

configure_file(${CMAKE_CURRENT_LIST_DIR}/seed.h.in seed.h)

set(RANDOM_SEED_INCLUDE "${CMAKE_CURRENT_BINARY_DIR}")

